- id: git-prevent-commit-on-default
  name: Prevent a commit on the default branch
  description: |
    Prevent a commit on the default branch
    A Pull Request should be used
  entry: dev-scripts/git-hooks/git-prevent-commit-on-default
  language: script
  pass_filenames: false
  always_run: true
  stages: [ pre-commit ]
  minimum_pre_commit_version: 3.2.0
- id: git-prevent-out-of-sync-commit
  name: Prevent a commit on a out-of-sync branch
  description: |
    Prevent a commit on a out-of-sync branch
    A pull should be done first
  entry: dev-scripts/git-hooks/git-prevent-out-of-sync-commit
  language: script
  pass_filenames: false
  always_run: true
  stages: [ pre-commit ]
  minimum_pre_commit_version: 3.2.0
- id: git-fetch
  name: git fetch
  description: |
    Fetch the latest changes from remote
  entry: dev-scripts/git-hooks/git-fetch
  language: script
  pass_filenames: false
  always_run: true
  stages: [ pre-commit ]
- id: maven-check-pom-xml
  name: check maven pom
  description: |
    Check a maven pom file
  entry: dev-scripts/git-hooks/maven-check-pom-xml
  language: script
  pass_filenames: false
  files: 'pom\.xml'
  stages: [ pre-commit ]
- id: javadoc-check
  name: check javadoc comments
  description: |
    A hook to check javadoc comment block
  entry: dev-scripts/git-hooks/javadoc-check
  language: script
  pass_filenames: true
  files: '\.java$'
  stages: [ pre-commit ]
- id: maven-install
  name: Install artifacts in the local repo
  description: |
    Install artifacts in the local repo by running maven install
  entry: dev-scripts/git-hooks/maven-install
  language: script
  # always_run = true is mandatory
  # as post commit does not filter on file names
  # https://pre-commit.com/#post-commit
  always_run: true
  stages: [ post-commit ]
