#!/usr/bin/env bash
# Configuration of git called by envrc

# Strict Bash
set -TCEeuo pipefail

source "$RM_DIR/bash/resource-manager-lib.sh"


# Git User Email
# Env name should be uppercase without minus
EMAIL_VAR="${RESOURCE_MANAGER_ENV_PREFIX}${ORGANISATION_ENV_NAME}_EMAIL"
EMAIL_VALUE="${!EMAIL_VAR}"
if rm_check_env_var "$EMAIL_VAR" "$EMAIL_VALUE" "$USER_ENV_SCOPE"; then

  git config user.email "$EMAIL_VALUE"
  echo "   Email: $EMAIL_VALUE"

fi

# Git signing key is the long format dir
# gpg --list-secret-keys --keyid-format=long
SIGNING_KEY_VAR="GIT_${ENV_ORGANISATION_NAME}_SIGNING_KEY"
SIGNING_KEY_VALUE="${!SIGNING_KEY_VAR}"
if rm_check_env_var "$SIGNING_KEY_VAR" "$SIGNING_KEY_VALUE" "$USER_ENV_SCOPE"; then

  git config user.signingkey "$SIGNING_KEY_VALUE"
  echo "   GPG Key: $SIGNING_KEY_VALUE"

  git config commit.gpgsign true
  echo "   GPG Sign: true"

fi

